wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678374500.47077
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.16
      5: 0.13.10
      8:
      - 5
id_lambda:
  desc: null
  value: 0.005
l2_lambda:
  desc: null
  value: 0.0002
lr_init:
  desc: null
  value: 0.05
lr_rampup:
  desc: null
  value: 0.05
trunc:
  desc: null
  value: 0.7
